# Generated by Django 4.0.3 on 2023-03-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0003_alter_listing_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product',
            field=models.CharField(choices=[('Sprayer', 'Sprayer'), ('Baler', 'Baler'), ('Cultivator', 'Cultivator'), ('Rotavator', 'Rotavator'), ('Plough', 'Plough'), ('Trailer', 'Trailer'), ('Tractor', 'Tractor'), ('Seed Drill', 'Seed_Drill'), ('Harvester', 'Harvester')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ratecriteria',
            field=models.CharField(choices=[('D', 'per day'), ('H', 'per hour'), ('K', 'per Km')], max_length=1),
        ),
    ]
