# Generated by Django 4.0.3 on 2023-03-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0004_alter_listing_product_alter_listing_ratecriteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='user',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='listing',
            name='product',
            field=models.CharField(choices=[('Seed Drill', 'Seed_Drill'), ('Cultivator', 'Cultivator'), ('Tractor', 'Tractor'), ('Rotavator', 'Rotavator'), ('Harvester', 'Harvester'), ('Sprayer', 'Sprayer'), ('Trailer', 'Trailer'), ('Plough', 'Plough'), ('Baler', 'Baler')], max_length=50),
        ),
    ]
