# Generated by Django 4.0.3 on 2023-03-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0006_alter_listing_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product',
            field=models.CharField(choices=[('Sprayer', 'Sprayer'), ('Tractor', 'Tractor'), ('Harvester', 'Harvester'), ('Cultivator', 'Cultivator'), ('Seed Drill', 'Seed_Drill'), ('Plough', 'Plough'), ('Trailer', 'Trailer'), ('Baler', 'Baler'), ('Rotavator', 'Rotavator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ratecriteria',
            field=models.CharField(choices=[('K', 'per Km'), ('D', 'per day'), ('H', 'per hour')], max_length=1),
        ),
    ]
