# Generated by Django 4.0.3 on 2023-03-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0007_alter_listing_product_alter_listing_ratecriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product',
            field=models.CharField(choices=[('Plough', 'Plough'), ('Cultivator', 'Cultivator'), ('Seed Drill', 'Seed_Drill'), ('Baler', 'Baler'), ('Rotavator', 'Rotavator'), ('Harvester', 'Harvester'), ('Trailer', 'Trailer'), ('Tractor', 'Tractor'), ('Sprayer', 'Sprayer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ratecriteria',
            field=models.CharField(choices=[('H', 'per hour'), ('K', 'per Km'), ('D', 'per day')], max_length=1),
        ),
    ]
