# Generated by Django 4.0.3 on 2023-03-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0008_alter_listing_product_alter_listing_ratecriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='availibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='product',
            field=models.CharField(choices=[('Trailer', 'Trailer'), ('Cultivator', 'Cultivator'), ('Harvester', 'Harvester'), ('Seed Drill', 'Seed_Drill'), ('Sprayer', 'Sprayer'), ('Baler', 'Baler'), ('Plough', 'Plough'), ('Tractor', 'Tractor'), ('Rotavator', 'Rotavator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ratecriteria',
            field=models.CharField(choices=[('D', 'per day'), ('K', 'per Km'), ('H', 'per hour')], max_length=1),
        ),
    ]
